# prometheus.yml
global:
  scrape_interval: 5s
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
#  external_labels:
#    monitor: 'my-monitor'
#scrape_configs:
#  - job_name: 'prometheus'
#    target_groups:
#      - targets: ['localhost:9090']
#  - job_name: 'node-exporter'
#    target_groups:
#      - targets: ['node-exporter:9100']
#

scrape_configs:
  - job_name: 'person-app'
    metrics_path: '/actuator/prometheus' #our REST endpoint for metrics
    static_configs:
      - targets: ['app:8080'] # Target address to scrape metrics from
